#!/bin/sh


#使用此脚本首先应使用root帐户安装cronolog
#yum -y install cronolog
#此脚本可以实现以start和stop方式启动或关闭，并且日志将按日期方式输出
#wget http://download-ib01.fedoraproject.org/pub/epel/6/x86_64/Packages/c/cronolog-1.6.2-10.el6.x86_64.rpm
#rpm -ivh cronolog-1.6.2-10.el6.x86_64.rpm

CRONOLOG_INSTALLED=0
CRONOLOG_PATH=
check_cronolog() {
    # PS some OS location: /usr/sbin/cronolog OR /usr/local/sbin/cronolog OR /usr/bin/cronolog(ubuntu)
    local cronolog_path=/usr/local/sbin/cronolog
    if [ ! -f "$cronolog_path" ]; then
      cronolog_path=/usr/sbin/cronolog
      if [ ! -f "$cronolog_path" ]; then
        cronolog_path=/usr/bin/cronolog
        if [ ! -f "$cronolog_path" ]; then
          wget http://download-ib01.fedoraproject.org/pub/epel/6/x86_64/Packages/c/cronolog-1.6.2-10.el6.x86_64.rpm
          rpm -ivh cronolog-1.6.2-10.el6.x86_64.rpm
          if [ $CRONOLOG_INSTALLED -eq 0 ]; then
            CRONOLOG_INSTALLED=1
            return check_cronolog
          else
            return 0
          fi
        fi
      fi
    fi
    CRONOLOG_PATH=$cronolog_path
    return 1
}
check_cronolog
if [ $? -eq 0 ]; then
  echo 'no found cronolog,please execute > yum -y install cronolog'
  exit -1
fi

JARPATH=/u01/mica-mqtt-spring-boot-starter-example
JARNAME=mica-mqtt-spring-boot-starter-example
cd $JARPATH

case "$1" in

  start)
    nohup java -Xmx128m -jar $JARPATH/$JARNAME.jar 2>&1 | $CRONOLOG_PATH ./logs/nohup_%Y%m%d.log &
    echo $[$!-1] > $JARPATH/$JARNAME.pid
    ;;

  stop)
    kill -9  `cat $JARPATH/$JARNAME.pid`
    rm -rf $JARPATH/$JARNAME.pid
    ;;

  restart)
    $0 stop
    sleep 1
    $0 start
    ;;

  *)
    echo "Usage: run.sh {start|stop|restart}"
    ;;

esac

exit 0

